name: Testing Fast API App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-and-lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
            python-version: 3.10.0


      - name: Install Poetry
        run:  pip3 install poetry

      - name: Config Poetry
        run:  poetry config virtualenvs.create false

      - name: Install project dependencies
        run:  poetry install

      - name: Run tests
        run:  pytest --cov=app 
        env: 
            FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
            auto_fix: true
            black: true
            black_auto_fix: true
